#!/usr/bin/env bash
# Install nginx on web-01 server listening on port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
service nginx reload
