#!/usr/bin/env bash
# Configure Nginx server to redirect /redirect_me to another page with a "301 Moved Permanently" redirect

apt-get update

apt-get install -y nginx

mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

# Configure Nginx default site to handle redirection
printf '%s\n' "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration changes
service nginx restart