#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Create an index.html file with content
echo "Hello World!" > /var/www/html/index.html

# Create a custom 404.html file with content
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Define the Nginx server block configuration
server_config=$(cat <<EOL
server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOL
)

# Apply the server configuration to the default Nginx site configuration
echo "$server_config" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
