#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#*    Enables management via the init script.
#*    Distributes requests using a round-robin algorithm.

apt-get update
apt-get install -y haproxy

printf %s "
frontend hbnb-lb_front
        bind *:80
        mode http
        default_backend hbnb-lb_back
backend hbnb-lb_back
        balance roundrobin
        server 309064-web-01 	100.25.165.225:80 check
        server 309064-web-01 18.233.65.83:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
