#!/usr/bin/env bash
#gives details of the etc file
while IFS=':' read -r username passwd uid gud uidinfo home shell;
do
        echo "The user $username is part of the $gud gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $uidinfo"
done < '/etc/passwd'
