#!/usr/bin/env bash
#Displays the content of the current directory
#In a list format Where only the part of the name after the first dash is displayed
for i in *;
do
        if [[ -f $i ]];
        then
                part_after_dash=$(echo "$i" | cut -d "-" -f 2)
                echo "$part_after_dash"
        fi
done
